ClinicaWeb/ClinicaWeb/Models/ClinicaDB/Paciente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaWeb.Models.ClinicaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int PersonaId { get; set; }
        public System.DateTime FRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual Persona Persona { get; set; }
    }
}

ClinicaWeb/ClinicaWeb/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicaWeb.Models.ClinicaDB;

namespace ClinicaWeb.Controllers
{
    public class PacienteController : Controller
    {
        private ClinicaDBContext db = new ClinicaDBContext();

        //// GET: Paciente
        //public ActionResult Index()
        //{
        //    var paciente = db.Paciente.Include(p => p.Persona);
        //    return View(paciente.ToList());
        //}

        //// GET: Paciente/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Paciente paciente = db.Paciente.Find(id);
        //    if (paciente == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(paciente);
        //}

        //// GET: Paciente/Create
        //public ActionResult Create()
        //{
        //    ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre");
        //    return View();
        //}

        // POST: Paciente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,UserName,Password,PersonaId,FRegistro")] Paciente paciente)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Paciente.Add(paciente);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre", paciente.PersonaId);
        //    return View(paciente);
        //}

        // GET: Paciente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            //ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre", paciente.PersonaId);
            return View(paciente);
        }

        // POST: Paciente/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                Paciente model = new Paciente
                {
                    Id = paciente.Id,
                    FRegistro = paciente.FRegistro,
                    PersonaId = paciente.PersonaId,
                    UserName = paciente.UserName.ToUpper(),
                    Password = paciente.Password.ToLower()
                };

                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Persona", new { id = paciente.PersonaId, type = PersonaType.Paciente });
            }

            //ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre", paciente.PersonaId);
            return View(paciente);
        }

        //// GET: Paciente/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Paciente paciente = db.Paciente.Find(id);
        //    if (paciente == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(paciente);
        //}

        //// POST: Paciente/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Paciente paciente = db.Paciente.Find(id);
        //    db.Paciente.Remove(paciente);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaWeb/ClinicaWeb/Views/Paciente/Create.cshtml
@model ClinicaWeb.Models.ClinicaDB.Paciente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonaId, "PersonaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClinicaWeb/ClinicaWeb/Views/Paciente/Delete.cshtml
@model ClinicaWeb.Models.ClinicaDB.Paciente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persona.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClinicaWeb/ClinicaWeb/Views/Paciente/Details.cshtml
@model ClinicaWeb.Models.ClinicaDB.Paciente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persona.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClinicaWeb/ClinicaWeb/Views/Paciente/Edit.cshtml
@model ClinicaWeb.Models.ClinicaDB.Paciente

@{
    ViewBag.Title = "Edit";
}

<!-- Content Header (Page header) -->
@*<section class="content-header">
        <h1>
            Page Header
            <small>Optional description</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>*@

<!-- Main content -->
<section class="content">
    @Html.Partial("~/Views/Persona/_DetailsPartial.cshtml", Model.Persona, new ViewDataDictionary { { "PersonaType", ClinicaWeb.Controllers.PersonaType.Paciente } })
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Cuenta usuario</h3>
        </div><!-- /.box-header -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PersonaId)
            @Html.HiddenFor(model => model.FRegistro)

            <div class="box-body">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="userName">Nombre usuario</label>
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control text-upper", @id = "userName" } })
                    </div>
                    <div class="col-md-6 form-group">
                        <label for="password">Contraseña</label>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control text-lower", @id = "password" } })
                    </div>
                </div><!-- /.row -->
            </div><!-- /.box-body -->
            <div class="box-footer">
                <a href="@Url.Action("Details", "Persona", new { id = Model.PersonaId, type = ClinicaWeb.Controllers.PersonaType.Paciente })" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-primary pull-right" style="width: 100px;">Guardar</button>
            </div>
        }
    </div><!-- /.box -->
</section><!-- /.content -->

ClinicaWeb/ClinicaWeb/Views/Paciente/Index.cshtml
@model IEnumerable<ClinicaWeb.Models.ClinicaDB.Paciente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Persona.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FRegistro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Persona.Nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ClinicaWeb/ClinicaWeb/Views/Paciente/_DetailsPartial.cshtml
@model ClinicaWeb.Models.ClinicaDB.Paciente

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Cuenta de usuario</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-6 form-group">
                <label for="firstName">Nombre usuario</label>
                <div>
                    @Html.DisplayFor(model => model.UserName)
                </div>
            </div>
            <div class="col-md-6 form-group">
                <label for="lastName">Contraseña</label>
                <div>
                    @Html.DisplayFor(model => model.Password)
                </div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-body -->
    <div class="box-footer">
        <a href="@Url.Action("Edit", "Paciente", new { id = Model.Id, type = ViewBag.PersonaType })" class="btn btn-primary pull-right">Editar</a>
    </div>
</div><!-- /.box -->