ClinicaWeb/ClinicaWeb/Models/ClinicaDB/Agenda.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaWeb.Models.ClinicaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agenda()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public int Id { get; set; }
        public System.DateTime FAgenda { get; set; }
        public string Estado { get; set; }
        public int EmpleadoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}

ClinicaWeb/ClinicaWeb/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicaWeb.Models.ClinicaDB;

namespace ClinicaWeb.Controllers
{
    public class AgendaController : Controller
    {
        private ClinicaDBContext db = new ClinicaDBContext();

        // GET: Agenda
        public ActionResult Index(int id)
        {
            ViewBag.Agendas = db.Agenda.Where(x => x.FAgenda >= DateTime.Today && x.EmpleadoId == id);
            return View(new Agenda
            {
                FAgenda = DateTime.Now,
                EmpleadoId = id,
                Estado = "A",
                Empleado = db.Empleado.Include(x => x.Persona).SingleOrDefault(x => x.Id == id)
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Agenda.Add(agenda);
                db.SaveChanges();
            }
            return RedirectToAction("Index", new { id = agenda.EmpleadoId });
        }

        // GET: Agenda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // GET: Agenda/Create
        public ActionResult Create()
        {
            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado");
            return View();
        }

        // POST: Agenda/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FAgenda,Estado,EmpleadoId")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Agenda.Add(agenda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado", agenda.EmpleadoId);
            return View(agenda);
        }

        // GET: Agenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado", agenda.EmpleadoId);
            return View(agenda);
        }

        // POST: Agenda/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FAgenda,Estado,EmpleadoId")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado", agenda.EmpleadoId);
            return View(agenda);
        }

        // GET: Agenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agenda agenda = db.Agenda.Find(id);
            db.Agenda.Remove(agenda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaWeb/ClinicaWeb/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicaWeb.Models.ClinicaDB;

namespace ClinicaWeb.Controllers
{
    public class PersonaController : Controller
    {
        private ClinicaDBContext db = new ClinicaDBContext();

        // GET: Persona
        public ActionResult Index(PersonaType? type)
        {
            List<Persona> list = new List<Persona>();
            ViewBag.PersonaType = type;

            switch (type)
            {
                case PersonaType.Paciente:
                    list = db.Paciente.Select(x => x.Persona).ToList();
                    break;
                case PersonaType.Empleado:
                    list = db.Empleado.Select(x => x.Persona).ToList();
                    break;
                default:
                    list = db.Persona.ToList();
                    break;
            }

            return View(list);
        }

        // GET: Persona/Details/5
        public ActionResult Details(int? id, PersonaType? type)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Persona.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }

            switch (type)
            {
                case PersonaType.Paciente:
                    ViewBag.Type = db.Paciente.SingleOrDefault(x => x.PersonaId == persona.Id);
                    break;
                case PersonaType.Empleado:
                    ViewBag.Type = db.Empleado.SingleOrDefault(x => x.PersonaId == persona.Id);
                    break;
                default:
                    break;
            }

            ViewBag.PersonaType = type;
            return View(persona);
        }

        // GET: Persona/Create
        public ActionResult Create(PersonaType? type)
        {
            ViewBag.PersonaType = type;
            return View();
        }

        // POST: Persona/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Persona persona, PersonaType? type)
        {
            if (ModelState.IsValid)
            {
                string controllerRequest = string.Empty;
                dynamic entityRequest = null;

                Persona model = new Persona
                {
                    Nombre = persona.Nombre.ToUpper(),
                    Apellido = persona.Apellido.ToUpper(),
                    TipoDocumento = persona.TipoDocumento.ToUpper(),
                    Identificacion = persona.Identificacion,
                    FNacimiento = DateTime.Now,
                    Genero = persona.Genero.ToUpper(),
                    Telefono = persona.Telefono,
                    Correo = persona.Correo.ToLower(),
                    Direccion = persona.Direccion.ToUpper()
                };

                db.Persona.Add(model);

                switch (type)
                {
                    case PersonaType.Paciente:
                        entityRequest = db.Paciente.Add(new Paciente
                        {
                            PersonaId = model.Id,
                            UserName = string.Empty,
                            Password = string.Empty,
                            FRegistro = DateTime.Now
                        });

                        controllerRequest = "Paciente";
                        break;
                    case PersonaType.Empleado:
                        entityRequest = db.Empleado.Add(new Empleado
                        {
                            PersonaId = model.Id,
                            TipoEmpleadoId = 1,
                            FRegistro = DateTime.Now,
                            Estado = "A"
                        });

                        controllerRequest = "Empleado";
                        break;
                    default:
                        break;
                }

                db.SaveChanges();
                return RedirectToAction("Edit", controllerRequest, new { id = entityRequest.Id });
            }

            return View(persona);
        }

        // GET: Persona/Edit/5
        public ActionResult Edit(int? id, PersonaType? type)
        {
            ViewBag.PersonaType = type;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Persona.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Persona/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Persona persona, PersonaType? type)
        {
            if (ModelState.IsValid)
            {
                Persona model = new Persona
                {
                    Id = persona.Id,
                    Nombre = persona.Nombre.ToUpper(),
                    Apellido = persona.Apellido.ToUpper(),
                    TipoDocumento = persona.TipoDocumento.ToUpper(),
                    Identificacion = persona.Identificacion,
                    FNacimiento = DateTime.Now,
                    Genero = persona.Genero.ToUpper(),
                    Telefono = persona.Telefono,
                    Correo = persona.Correo.ToLower(),
                    Direccion = persona.Direccion.ToUpper()
                };

                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = model.Id, type = type });
            }
            return View(persona);
        }

        //// GET: Persona/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Persona persona = db.Persona.Find(id);
        //    if (persona == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(persona);
        //}

        //// POST: Persona/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Persona persona = db.Persona.Find(id);
        //    db.Persona.Remove(persona);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

    public enum PersonaType
    {
        Paciente,
        Empleado
    }
}

ClinicaWeb/ClinicaWeb/Views/Agenda/Create.cshtml
@model ClinicaWeb.Models.ClinicaDB.Agenda

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FAgenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FAgenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FAgenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpleadoId, "EmpleadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpleadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpleadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClinicaWeb/ClinicaWeb/Views/Agenda/Delete.cshtml
@model ClinicaWeb.Models.ClinicaDB.Agenda

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FAgenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FAgenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleado.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClinicaWeb/ClinicaWeb/Views/Agenda/Details.cshtml
@model ClinicaWeb.Models.ClinicaDB.Agenda

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FAgenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FAgenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleado.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClinicaWeb/ClinicaWeb/Views/Agenda/Edit.cshtml
@model ClinicaWeb.Models.ClinicaDB.Agenda

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FAgenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FAgenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FAgenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpleadoId, "EmpleadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpleadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpleadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClinicaWeb/ClinicaWeb/Views/Agenda/Index.cshtml
@model ClinicaWeb.Models.ClinicaDB.Agenda
@*@model IEnumerable<ClinicaWeb.Models.ClinicaDB.Agenda>*@

@{
    ViewBag.Title = "Index";
}

<!-- Content Header (Page header) -->
@*<section class="content-header">
        <h1>
            Page Header
            <small>Optional description</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>*@

<!-- Main content -->
<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Programar agenda @string.Join(" ", " » ", Model.Empleado.Persona.Nombre, Model.Empleado.Persona.Apellido)</h3>
        </div><!-- /.box-header -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.EmpleadoId);
            @Html.HiddenFor(model => model.Estado);
            
            <div class="box-body">
                <div class="col-md-6 input-group">
                    @Html.EditorFor(model => model.FAgenda, new { htmlAttributes = new { @class = "form-control", @data_inputmask = "'alias': 'yyyy-mm-dd'", @data_mask = string.Empty, @type = "text" } })
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                    </div><!-- /btn-group -->
                </div><!-- /input-group -->
            </div><!-- /.box-body -->
            <div class="box-footer">
                <a href="@Url.Action("Details", "Persona", new { id = Model.Empleado.PersonaId, type = ClinicaWeb.Controllers.PersonaType.Empleado })" class="btn btn-default">Volver</a>
            </div>
        }
    </div><!-- /.box -->
    <!-- Your Page Content Here -->
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Listado agendas</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Estado</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ClinicaWeb.Models.ClinicaDB.Agenda item in ViewBag.Agendas)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FAgenda)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Estado)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->


@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FAgenda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Empleado.Estado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FAgenda)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Empleado.Estado)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>*@