ClinicaWeb/ClinicaWeb/Models/ClinicaDB/Empleado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaWeb.Models.ClinicaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public System.DateTime FRegistro { get; set; }
        public string Estado { get; set; }
        public int PersonaId { get; set; }
        public int TipoEmpleadoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TipoEmpleado TipoEmpleado { get; set; }
    }
}

ClinicaWeb/ClinicaWeb/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicaWeb.Models.ClinicaDB;

namespace ClinicaWeb.Controllers
{
    public class AgendaController : Controller
    {
        private ClinicaDBContext db = new ClinicaDBContext();

        // GET: Agenda
        public ActionResult Index(int id)
        {
            ViewBag.Agendas = db.Agenda.Where(x => x.FAgenda >= DateTime.Today && x.EmpleadoId == id);
            return View(new Agenda
            {
                FAgenda = DateTime.Now,
                EmpleadoId = id,
                Estado = "A",
                Empleado = db.Empleado.Include(x => x.Persona).SingleOrDefault(x => x.Id == id)
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Agenda.Add(agenda);
                db.SaveChanges();
            }
            return RedirectToAction("Index", new { id = agenda.EmpleadoId });
        }

        // GET: Agenda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // GET: Agenda/Create
        public ActionResult Create()
        {
            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado");
            return View();
        }

        // POST: Agenda/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FAgenda,Estado,EmpleadoId")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Agenda.Add(agenda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado", agenda.EmpleadoId);
            return View(agenda);
        }

        // GET: Agenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado", agenda.EmpleadoId);
            return View(agenda);
        }

        // POST: Agenda/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FAgenda,Estado,EmpleadoId")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleado, "Id", "Estado", agenda.EmpleadoId);
            return View(agenda);
        }

        // GET: Agenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agenda agenda = db.Agenda.Find(id);
            db.Agenda.Remove(agenda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaWeb/ClinicaWeb/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicaWeb.Models.ClinicaDB;

namespace ClinicaWeb.Controllers
{
    public class EmpleadoController : Controller
    {
        private ClinicaDBContext db = new ClinicaDBContext();

        //// GET: Empleado
        //public ActionResult Index()
        //{
        //    var empleado = db.Empleado.Include(e => e.Persona).Include(e => e.TipoEmpleado);
        //    return View(empleado.ToList());
        //}

        // GET: Empleado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleado.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        //// GET: Empleado/Create
        //public ActionResult Create()
        //{
        //    ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre");
        //    ViewBag.TipoEmpleadoId = new SelectList(db.TipoEmpleado, "Id", "Nombre");
        //    return View();
        //}

        //// POST: Empleado/Create
        //// Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        //// más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,FRegistro,Estado,PersonaId,TipoEmpleadoId")] Empleado empleado)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Empleado.Add(empleado);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre", empleado.PersonaId);
        //    ViewBag.TipoEmpleadoId = new SelectList(db.TipoEmpleado, "Id", "Nombre", empleado.TipoEmpleadoId);
        //    return View(empleado);
        //}

        // GET: Empleado/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleado.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            //ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre", empleado.PersonaId);
            ViewBag.TipoEmpleadoId = new SelectList(db.TipoEmpleado, "Id", "Nombre", empleado.TipoEmpleadoId);
            return View(empleado);
        }

        // POST: Empleado/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Persona", new { id = empleado.PersonaId, type = PersonaType.Empleado });
            }
            //ViewBag.PersonaId = new SelectList(db.Persona, "Id", "Nombre", empleado.PersonaId);
            ViewBag.TipoEmpleadoId = new SelectList(db.TipoEmpleado, "Id", "Nombre", empleado.TipoEmpleadoId);
            return View(empleado);
        }

        // GET: Empleado/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Empleado empleado = db.Empleado.Find(id);
        //    if (empleado == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(empleado);
        //}

        //// POST: Empleado/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Empleado empleado = db.Empleado.Find(id);
        //    db.Empleado.Remove(empleado);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaWeb/ClinicaWeb/Views/Empleado/Create.cshtml
@model ClinicaWeb.Models.ClinicaDB.Empleado

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonaId, "PersonaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoEmpleadoId, "TipoEmpleadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoEmpleadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoEmpleadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClinicaWeb/ClinicaWeb/Views/Empleado/Delete.cshtml
@model ClinicaWeb.Models.ClinicaDB.Empleado

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persona.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoEmpleado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoEmpleado.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClinicaWeb/ClinicaWeb/Views/Empleado/Details.cshtml
@model ClinicaWeb.Models.ClinicaDB.Empleado

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persona.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoEmpleado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoEmpleado.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClinicaWeb/ClinicaWeb/Views/Empleado/Edit.cshtml
@model ClinicaWeb.Models.ClinicaDB.Empleado

@{
    ViewBag.Title = "Edit";
}

<!-- Content Header (Page header) -->
@*<section class="content-header">
        <h1>
            Page Header
            <small>Optional description</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>*@

<!-- Main content -->
<section class="content">
    @Html.Partial("~/Views/Persona/_DetailsPartial.cshtml", Model.Persona, new ViewDataDictionary { { "PersonaType", ClinicaWeb.Controllers.PersonaType.Empleado } })
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Cargo</h3>
        </div><!-- /.box-header -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PersonaId)
            @Html.HiddenFor(model => model.FRegistro)
            @Html.HiddenFor(model => model.Estado)

            <div class="box-body">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label>Fecha registro</label>
                        <div>
                            @Html.DisplayFor(model => model.FRegistro, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="col-md-6 form-group">
                        <label>Nombre cargo</label>
                        @Html.DropDownList("TipoEmpleadoId", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div><!-- /.row -->
            </div><!-- /.box-body -->
            <div class="box-footer">
                <a href="@Url.Action("Details", "Persona", new { id = Model.PersonaId, type = ClinicaWeb.Controllers.PersonaType.Empleado })" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-primary pull-right" style="width: 100px;">Guardar</button>
            </div>
        }
    </div><!-- /.box -->
</section><!-- /.content -->

ClinicaWeb/ClinicaWeb/Views/Empleado/Index.cshtml
@model IEnumerable<ClinicaWeb.Models.ClinicaDB.Empleado>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Persona.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoEmpleado.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FRegistro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Persona.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoEmpleado.Nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ClinicaWeb/ClinicaWeb/Views/Empleado/_DetailsPartial.cshtml
@model ClinicaWeb.Models.ClinicaDB.Empleado

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Cargo</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-6 form-group">
                <label for="firstName">Fecha registro</label>
                <div>
                    @Html.DisplayFor(model => model.FRegistro)
                </div>
            </div>
            <div class="col-md-6 form-group">
                <label for="lastName">Nombre cargo</label>
                <div>
                    @Html.DisplayFor(model => model.TipoEmpleado.Nombre)
                </div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.box-body -->
    <div class="box-footer">
        @if (Model.TipoEmpleado.Id == 2)
        {
            <a href="@Url.Action("Index", "Agenda", new { id = Model.Id })" class="btn btn-success">Ver agenda</a>
        }
        <a href="@Url.Action("Edit", "Empleado", new { id = Model.Id, type = ViewBag.PersonaType })" class="btn btn-primary pull-right">Editar</a>
    </div>
</div><!-- /.box -->